config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/show/:id' => 'topics#show', as: :topics_show
  post 'topics/create' => 'topics#create'
  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
  post 'posts/create' => 'post#create', as: :post_create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
    @post = Post.new(params[:post].permit(:topic_id, :name, :body))
    @post.save
    redirect_to topics_show_path(params[:post]['topic_id'])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @newTopic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @newpost = Post.new(:topic_id => params[:id])
    @posts = Post.where(topic_id: params[:id])
  end

  def create
    @topic = Topic.new(params[:topic].permit(:title))
    @topic.save
    redirect_to topics_index_path
  end

  def delete
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.erb
<div class="container">
  <h1>トピック一覧</h1>
  <ul class="list-group">
    <% @topics.each do |topic| %>
      <li class="list-group-item">
        <%= link_to topic.title, topics_show_path(topic.id) %>
        <%= link_to "削除", topic_delete_path(topic.id), class: 'btn btn-info btn-xs', method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
      </li>
    <% end %>
  </ul>
  <h1>トピック新規登録</h1>
  <%= form_for @newTopic, :url => {:action => 'create'} do |f| %>
    <%= f.text_field :title %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <h1><%= @topic.title %></h1>
  <% @posts.each_with_index do |post , idx| %>
    <ul class="list-group">
      <li class="list-group-item">
        <%= idx + 1 %>. <%= post.name %> : <%= post.body %>
      </li>
      <% end %>
    </ul>
  <h3>新規書き込み</h3>
  <%= form_for @newpost, :url => post_create_path do |f| %>
  <p>お名前</p>
  <p><%= f.text_field :name %></p>
  <p>本文</p>
  <p><%= f.text_area :body %></p>
  <%= f.hidden_field :topic_id %>
  <%= f.submit class: "btn btn-primary"%>
  <% end %>
  </div>
</div>